;           Gerber:: Drill Report             
;           =====================             
;    Unit                   : metric
;    Format                 : 4.4, Leading Zeros Suppressed
;    Co-ordinate data Mode  : Absolute Data mode
;+----------------------------------------+
;|  D R I L L   T O O L S   T A B L E     |
;+----------------------------------------+
;|    Drill    |    Tool    |    Drill    |
;|    Tool     |    Size    |    Count    |
;+----------------------------------------+
;|          T01|    0.800000|            3|
;+----------------------------------------+

M48

METRIC,LZ,0000.0000
T01C0.800000
%
M71
G90
T01
X-006021Y-0097245
X-005606Y-0097215
X-005468Y-00972011

M30
